# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='secrets_like', to='secrets_app.User'),
        ),
    ]
