# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doge_secret', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.BooleanField(),
        ),
    ]
