# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doge_secret', '0002_auto_20170421_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
