# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='like',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
