# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_auto_20170421_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='user_id',
        ),
    ]
