# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0007_auto_20170421_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
